version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'monthly'
    - package-ecosystem: 'composer'
      directory: '/'
      schedule:
          interval: 'daily'
