name: Generate Laravel Commands
on:
  workflow_dispatch:
  schedule:
  # At 08:00 Friday
  - cron: "0 8 * * 5"
jobs:
    generate:
        name: Generate Commands
        runs-on: ubuntu-latest
        strategy:
            matrix:
                laravel: [6, 7, 8, 9, 10]
        steps:
            - name: Check out code
              uses: actions/checkout@v3
            - name: Set up git user
              run: git config --global user.name ${GITHUB_ACTOR}
            - name: Set up git email
              run: git config --global user.email ${GITHUB_ACTOR}@users.noreply.github.com

            - name: Setup PHP, with Composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                php-version: 8.2
                extensions: dom, curl, libxml, mbstring, zip
                tools: composer:v2

            - name: Install Laravel
              run: composer create-project --no-progress laravel/laravel="^${{ matrix.laravel }}" /tmp/laravel

            - name: Run Generator Command
              run: |
                cd /tmp/laravel
                cat ${{ github.workspace }}/scripts/generate | php artisan tinker > /tmp/${{ matrix.laravel }}.x.json | true

            - name: Update main branch
              run: |
                  n=0
                  until [ "$n" -ge 10 ]
                  do
                    git fetch --all
                    git reset --hard HEAD
                    git clean -f -d
                    git pull || true
                    cp /tmp/${{ matrix.laravel }}.x.json ${{ github.workspace }}/pages/api/_data/
                    git add -A || true
                    git commit -am 'Build Laravel version v${{ matrix.laravel }}' || true
                    git push --force && break
                    n=$((n+1))
                    sleep 15
                  done
              continue-on-error: true
